### ISSUE TITLE
What The Fuck Is That

### ISSUE THREAD

**Issue by desertkun** [SpycerLviv/HangmanGame-Python#1]
This is probably the purest shitcode I've ever seen.  Did you know python has functions? Have you considered to use a dict instead of thousands of `if`? Did you read `PEP8`?

How is that happened that write this to find a `z` letter:

```
if word[0] != "Z" and word[0] != "z" and word[1] != "Z" and word[1] != "z" and word[2] != "Z" and word[2] != "z" and word[3] != "Z" and word[3] != "z" and word[4] != "Z" and word[4] != "z" and word[5] != "Z" and word[5] != "z" and word[6] != "Z" and word[6] != "z" :
```
And then you call some functions like `guessChar.isalpha()`? How about `word.lower().find("z")`? 

You put so much effort into this and yet I bet this code can be optimized to ~60 lines

**Comment by SpycerLviv** [comment]
Oh, man, calm down.  There is a folder called 'generators'. I didn't write those thousands of lines. Only a generator that creates code that creates a game :)
